const allDevices = [
  {
    _manager: {
      _activePromises: [Object],
      _activeSubscriptions: [Object],
      _errorCodesToMessagesMapping: [Object],
      _eventEmitter: [NativeEventEmitter],
      _scanEventSubscription: [Object],
      _uniqueId: 0,
    },
    id: "7F:3B:DD:E0:14:C6",
    isConnectable: null,
    localName: null,
    manufacturerData: "TAAMDgBUM12GsYI1BcLAe4l0EAZHHZKxZ0g=",
    mtu: 23,
    name: null,
    overflowServiceUUIDs: null,
    rssi: -97,
    serviceData: null,
    serviceUUIDs: null,
    solicitedServiceUUIDs: null,
    txPowerLevel: null,
  },
  {
    _manager: {
      _activePromises: [Object],
      _activeSubscriptions: [Object],
      _errorCodesToMessagesMapping: [Object],
      _eventEmitter: [NativeEventEmitter],
      _scanEventSubscription: [Object],
      _uniqueId: 0,
    },
    id: "23:89:BD:54:0B:93",
    isConnectable: null,
    localName: null,
    manufacturerData: "TAAWCMEAdgofkmPf",
    mtu: 23,
    name: null,
    overflowServiceUUIDs: null,
    rssi: -31,
    serviceData: null,
    serviceUUIDs: null,
    solicitedServiceUUIDs: null,
    txPowerLevel: null,
  },
  {
    _manager: {
      _activePromises: [Object],
      _activeSubscriptions: [Object],
      _errorCodesToMessagesMapping: [Object],
      _eventEmitter: [NativeEventEmitter],
      _scanEventSubscription: [Object],
      _uniqueId: 0,
    },
    id: "16:85:8C:CF:2B:9A",
    isConnectable: null,
    localName: null,
    manufacturerData: "TAAJBgPprBQKBw==",
    mtu: 23,
    name: null,
    overflowServiceUUIDs: null,
    rssi: -70,
    serviceData: null,
    serviceUUIDs: null,
    solicitedServiceUUIDs: null,
    txPowerLevel: null,
  },
  {
    _manager: {
      _activePromises: [Object],
      _activeSubscriptions: [Object],
      _errorCodesToMessagesMapping: [Object],
      _eventEmitter: [NativeEventEmitter],
      _scanEventSubscription: [Object],
      _uniqueId: 0,
    },
    id: "6D:90:84:4F:E8:D4",
    isConnectable: null,
    localName: null,
    manufacturerData: "TAAQBzwbD2bZ2gg=",
    mtu: 23,
    name: null,
    overflowServiceUUIDs: null,
    rssi: -28,
    serviceData: null,
    serviceUUIDs: null,
    solicitedServiceUUIDs: null,
    txPowerLevel: 8,
  },
  {
    _manager: {
      _activePromises: [Object],
      _activeSubscriptions: [Object],
      _errorCodesToMessagesMapping: [Object],
      _eventEmitter: [NativeEventEmitter],
      _scanEventSubscription: [Object],
      _uniqueId: 0,
    },
    id: "EB:2B:E0:63:B0:E3",
    isConnectable: null,
    localName: null,
    manufacturerData: "TAASAgAA",
    mtu: 23,
    name: null,
    overflowServiceUUIDs: null,
    rssi: -67,
    serviceData: null,
    serviceUUIDs: null,
    solicitedServiceUUIDs: null,
    txPowerLevel: null,
  },
  {
    _manager: {
      _activePromises: [Object],
      _activeSubscriptions: [Object],
      _errorCodesToMessagesMapping: [Object],
      _eventEmitter: [NativeEventEmitter],
      _scanEventSubscription: [Object],
      _uniqueId: 0,
    },
    id: "57:A7:95:B0:6E:E2",
    isConnectable: null,
    localName: null,
    manufacturerData: "TAAMDgBUM12GsYI1BcLAe4l0EAZHHZKxZ0g=",
    mtu: 23,
    name: null,
    overflowServiceUUIDs: null,
    rssi: -95,
    serviceData: null,
    serviceUUIDs: null,
    solicitedServiceUUIDs: null,
    txPowerLevel: null,
  },
  {
    _manager: {
      _activePromises: [Object],
      _activeSubscriptions: [Object],
      _errorCodesToMessagesMapping: [Object],
      _eventEmitter: [NativeEventEmitter],
      _scanEventSubscription: [Object],
      _uniqueId: 0,
    },
    id: "E5:94:F6:0A:27:A0",
    isConnectable: null,
    localName: null,
    manufacturerData: "TAASAgAC",
    mtu: 23,
    name: null,
    overflowServiceUUIDs: null,
    rssi: -87,
    serviceData: null,
    serviceUUIDs: null,
    solicitedServiceUUIDs: null,
    txPowerLevel: null,
  },
  {
    _manager: {
      _activePromises: [Object],
      _activeSubscriptions: [Object],
      _errorCodesToMessagesMapping: [Object],
      _eventEmitter: [NativeEventEmitter],
      _scanEventSubscription: [Object],
      _uniqueId: 0,
    },
    id: "D4:B6:F0:64:28:BD",
    isConnectable: null,
    localName: null,
    manufacturerData: "TAASAgAA",
    mtu: 23,
    name: null,
    overflowServiceUUIDs: null,
    rssi: -28,
    serviceData: null,
    serviceUUIDs: null,
    solicitedServiceUUIDs: null,
    txPowerLevel: null,
  },
];
